searchguard:
  dynamic:
    http:
      xff:
        enabled: true
        remoteIpHeader: 'x-forwarded-for'
        proxiesHeader: 'x-forwarded-by'
        trustedProxies: '.*'
        internalProxies: '.*'
    authc:
      authentication_domain_proxy:
        enabled: true
        order: 1
        http_authenticator:
          challenge: false
          type: proxy
          config:
            user_header: 'X-Proxy-Remote-User'
            roles_header: 'x-proxy-roles'
        authentication_backend:
          type: noop
      authentication_domain_basic_internal:
        enabled: true
        order: 0
        http_authenticator:
          type: clientcert
          challenge: false
        authentication_backend:
          type: noop
